# Generated by Django 6.0.5 on 2026-05-21 23:07

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
